### ISSUE TITLE
Bold/strong text is hard to distinguish from regular text

### ISSUE THREAD

**Issue by flauschzelle** [prototypefund/demo-week-2020#14]
While proofreading the text of our project's page, I noticed that emphasized text (marked as bold or strong) does not stand out very much, because the font weight is only slightly bigger than the regular text's. 

I think it would be helpful for the readers if the bold/strong text parts would stand out more - maybe they could be a different color (I suggest white) in addition to the slightly bigger font weight?

**Comment by tanius** [comment]
If anyone is looking for a workaround for right now: I used underlined text via `<u> … </u>` to provide the additional highlighting. Not too pretty, but gets the job done. (And no, it's no longer deprecated in HTML5. Not in general, only if it could be confused with hyperlinks.)

**Comment by rudolfburgaj** [comment]
@flauschzelle only the regular weight was provided. In order to fix the issue, the BOLD weight is needed, which can be found here: https://blazetype.eu/typecatalogue/surt

**Comment by SaptakS** [comment]
I have also made `<b>` and `<strong>` render in `#ffffff` to emphasise more in https://github.com/prototypefund/demo-week-2020/commit/844dafd9c2ee3906930abda40601283ecd66e5c0
